### ISSUE TITLE
G2P transcribes "" as "j E"

### ISSUE THREAD

**Issue by G-Thor** [grammatek/ice-g2p#15]
The g2p for some reason transcribes the empty string as "j E". So if the input has a double space somewhere, the transcribed output adds a "j E" there.

**Comment by G-Thor** [comment]
Example:
Input: "takk fyrir jóhanna .  góðan dag góðir gestir . " **Double space between "." and "góðan" removed by Markdown in comment**
Output: "t_h a1 h k . f I:1 , r I0 r . j ou:1 , h a0 , n a0 .  **. j E:1** . k ou:1 , D a0 n . t a:1 G . k ou:1 , D I0 r . c E1 s , t I0 r . "

**Comment by bnika** [comment]
This is very strange, I'll have a look into that (but having the system say "yeah!" every now and then is also an interesting feature;)

**Comment by G-Thor** [comment]
It's a feature, not a bug!

**Comment by bnika** [comment]
fixed, for some reason the lstm model transcribes an empty string as 'j E', but of course the empty string shouldn't be handed over to the model at all
